
considerando o schema hr do freesql faça um comando para excluir cargos com job_id iniciando por 'AD_'
delete from hr.jobs where job_id like 'AD_%';

remova da tabela jobs cargos cujo salario maximo seja menor que 3000
delete from hr.jobs where max_salary < 3000;

delete todos os registros da tabela employees onde o funcionario foi contratado há mais de 30 anos
delete from hr.employee where hire_date > 30

utilize uma sub consulta para atualizar um salario de um funcionario qualquer para ser igual ao salario medio do seu departamento
update hr.employees set salary = (select avg(salary) from hr.employees) where employee_id = 1;


/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:


CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar os nomes dos países que possuem mais de 5 autores vinculados a instituições.*/
select i.pais,count(a.autorID) from instituicoes i inner join autores a on i.instituicaoID = a.instituicaoID group by i.pais having count(a.autorID) > 5;



/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar o nome dos autores e o nome das instituições às quais estão vinculados. Ordenar o resultado pelo nome dos autores.*/
select a.nome as nomeAutor, i.nome as nomeInstituicao from autores a inner join instituicoes i on a.instituicaoID = i.instituicaoID order by a.nome;



/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar os títulos dos artigos que possuem a palavra "inteligência" no resumo e que pertencem a revistas com ISSN iniciado por '123'.*/
select ar.titulo from artigos ar where ar.resumo like '%inteligência%' and ar.revistaID in (select revistaID from revista where issn like '123%');



/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar, para cada país, a quantidade total de autores vinculados a instituições desse país. Mostre no resultado o nome do país e a quantidade total de autores. Ordene o resultado por quantidade total de autores em ordem decrescente.*/

select i.pais, count(a.autorID) from instituicoes i inner join autores a on a.instituicaoID = i.instituicaoID group by i.pais order by count(a.autorID) desc;



Considerando o schema HR (Human Resources) do Oracle e utilizando o comando DML apropriado, aumente o salário em 5% para todos os funcionários contratados antes de 01/01/2005.
update hr.employees set salary = salary * 1.05 where hire_date < '01/01/2005';



Considerando o schema HR (Human Resources) do Oracle e utilizando o comando DML apropriado, remova da tabela jobs todos os cargos cujo salário máximo seja menor que 3000.
delete from hr.jobs where max_salary < 3000;


Considerando o schema HR (Human Resources) do Oracle e utilizando o comando DML apropriado, insira um novo funcionário na tabela employees fornecendo nome, sobrenome, email, data de contratação, ID do cargo e salário.
insert into hr.employees (first_name,last_name,email,hire_date,job_id,salary) values ('Arthur','Franca','arthur.fr.sc@gmail.com','13/5/2026, 12:00:00 AM','IT_PROG',2000);



Considerando o schema HR (Human Resources) do Oracle e utilizando o comando DML apropriado,  atualize o job_id de todos os funcionários cujo cargo atual seja 'IT_PROG' para 'SR_PROG'.
update hr.employees set job_id = 'SR_PROG' where job_id = 'IT_PROG';


/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50) );

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar quantas instituições existem em cada cidade. Mostre o nome da cidade e a respectiva quantidade de instituições. Ordene o resultado pela quantidade de instituições em ordem decrescente.*/
select pais, count(instituicaoID) from instituicoes group by pais order by count(instituicaoID) desc;





/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar o nome e o e-mail dos autores que não publicaram nenhum artigo. Ordene o resultado por nome do autor.*/

select nome, email from autores where autorID not in(select autorID from artigo_autor) order by nome;





/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar os nomes das instituições e a quantidade total de artigos publicados por seus autores.*/

select i.nome, count(aa.artigoID) from instituicoes i inner join autores a on a.instituicaoID = i.instituicaoID inner join artigo_autor aa on aa.autorID = a.autorID group by i.nome;




/*Considerando que as versões superiores à versão 12c do SGBD Oracle permitem utilizar  IDENTITY para geração automática de IDs e com relação ao script abaixo, responda à questão a seguir escrevendo comandos em SQL:

CREATE TABLE instituicoes (
instituicaoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,

pais VARCHAR2(50)

);

CREATE TABLE revista (
revistaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
issn VARCHAR2(20)
);

CREATE TABLE autores (
autorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
email VARCHAR2(100),
instituicaoID NUMBER,
CONSTRAINT fk_autor_instituicao
FOREIGN KEY (instituicaoID) REFERENCES instituicoes(instituicaoID)
);

CREATE TABLE artigos (
artigoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
resumo VARCHAR2(500),
palavrasChave VARCHAR2(200),
revistaID NUMBER,
CONSTRAINT fk_artigo_revista
FOREIGN KEY (revistaID) REFERENCES revista(revistaID)
);

CREATE TABLE artigo_autor (
artigoID NUMBER,
autorID NUMBER,
ordem NUMBER, -- posição do autor na lista
PRIMARY KEY (artigoID, autorID),
CONSTRAINT fk_artigoautor_artigo
FOREIGN KEY (artigoID) REFERENCES artigos(artigoID),
CONSTRAINT fk_artigoautor_autor
FOREIGN KEY (autorID) REFERENCES autores(autorID)
);

Listar, para cada revista, o número de artigos publicados. Mostre no resultado o nome da revista a quantidade de artigos publicados. Defina um alias para a quantidade de artigos. Ordene o resultado em ordem alfabética de nome da revista.*/

select r.nome, count(a.artigoID) as qunatidade_artigos from revista r inner join artigos a on a.revistaID = r.revistaID group by r.nome order by r.nome asc ;



